### ISSUE TITLE
Are you thinking of releasing a Swift version?

### ISSUE THREAD

**Issue by ejpusa** [jpsim/JPSThumbnailAnnotation#19]
Is there a Swift version on the horizon? thanks

**Comment by jpsim** [comment]
Hey, I like Swift as much as the next dev, but is there a reason why offering a Swift interface would significantly improve using JPSThumbnailAnnotation's Objective-C interface from Swift? The interface wouldn't really benefit from having support for generics or Swift-style enums or structs or any other reason I can think of.

I'm not opposed to it per-se, btw. Let me know what you think!

**Comment by nassarofficial** [comment]
So does this mean, we can't use JPSThumnail with swift, and if we could, how would this translate to swift?
    JPSThumbnail *empire = [[JPSThumbnail alloc] init];
    empire.image = [UIImage imageNamed:@"empire.jpg"];
    empire.title = @"Empire State Building";
    empire.subtitle = @"NYC Landmark";
    empire.coordinate = CLLocationCoordinate2DMake(40.75f, -73.99f);
    empire.disclosureBlock = ^{ NSLog(@"selected Empire"); };

**Comment by jpsim** [comment]
You can definitely use this from Swift. Here's what that snippet would look like:

```swift
let empire = JPSThumbnail()
empire.image = UIImage(named: "empire.jpg")
empire.title = "Empire State Building"
empire.subtitle = "NYC Landmark"
empire.coordinate = CLLocationCoordinate2DMake(40.75, -73.99)
empire.disclosureBlock = { println("selected Empire") }
```

**Comment by nassarofficial** [comment]
Im sorry, Could you help me to get at least one marker on? This is my code: 
    override func viewDidLoad() {
        super.viewDidLoad()
        mapView = MKMapView(frame: view.bounds)
        mapView.delegate = self
        view.addSubview(mapView)
        mapView.addAnnotations(annotations())
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }

    func annotations(){
        let empire = JPSThumbnail()
        empire.image = UIImage(named: "empire.jpg")
        empire.title = "Empire State Building"
        empire.subtitle = "NYC Landmark"
        empire.coordinate = CLLocationCoordinate2DMake(40.75, -73.99)
        empire.disclosureBlock = { println("selected Empire") }
    }
    
    func mapView(mapView: MKMapView!, viewForAnnotation annotation: MKAnnotation!) -> MKAnnotationView! {
        let view = MKPinAnnotationView(annotation: annotation, reuseIdentifier: "pin")
        view.image = UIImage() //imageWithColor(UIColor.redColor())
        
        return view
    }
    
    func mapView(mapView: MKMapView!, didSelectAnnotationView view: MKAnnotationView!) {
    }
    
    func mapView(mapView: MKMapView!, didDeselectAnnotationView view: MKAnnotationView!) {
    }

**Comment by jpsim** [comment]
Is your view controller conforming to the `MKMapViewDelegate` protocol?

**Comment by nassarofficial** [comment]
yes

**Comment by nassarofficial** [comment]
@jpsim could you please help me out, Im having a hard time making it work, Im clueless in Objective c

**Comment by jpsim** [comment]
I've pushed a Swift demo to the `swift-1.2` branch.

**Comment by nassarofficial** [comment]
I can't thank you enough for this!

**Comment by krishnaverma** [comment]
where is "swift-1.2" this swift version?

**Comment by jpsim** [comment]
https://github.com/jpsim/JPSThumbnailAnnotation/tree/swift-1.2
